site_name: Project Eucalyptus 🌿

docs_dir: docs

use_directory_urls: false

repo_url: https://github.com/Orbio-Earth/Project-Eucalyptus
edit_uri: ""

# Theming
theme:
features:
  - navigation.indexes
  - icon:
    repo: fontawesome/brands/github

# Navigation
nav:
  - Introduction: index.md
  - Data: Data.md
  - Radiative transfer: Radiative_Transfer.md
  - Model: Model.md
  - Validation: Validation.md
  - Postprocessing: Postprocessing.md
  - Landsat: Landsat.md
  - Hyperspectral: Hyperspectral.md

# Markdown Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
